
# Site metadata
# ---------------------

title: WAVE Festival

author:
  name: WAVE Festival
  email: tbd@tbd.tbd

description: >
  Women Amplify the Voice of Electroacoustic (WAVE) Music Festival

# Build settings
# ---------------------

remote_theme: jekyll/minima@d4d779a

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: solarized-light

  nav_pages:
    - call.md
    - contact.md
  