
# Site metadata
# ---------------------

title: WAVE Festival

author:
  name: WAVE Festival
  email: tbd@tbd.tbd

description: >
  Women Amplify the Voice of Electroacoustic (WAVE) Music Festival

# Build settings
# ---------------------

remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: solarized-light
  